import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import Navbar from "./navbar/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const cookies = headersList.get("cookie");
  const theme = cookies?.split(";").find((cookie) => cookie.includes("theme"));
  const selectedTheme = theme?.split("=")[1];



  return (
    <html lang="en" className={selectedTheme}>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
