import type { Metadata } from "next";
import { Cousine } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import Navbar from "./navbar/navbar";

const cousine = Cousine({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const cookies = headersList.get("cookie");
  const theme = cookies?.split(";").find((cookie) => cookie.includes("theme"));
  const selectedTheme = theme?.split("=")[1];

  return (
    <html lang="en" className={selectedTheme}>
      <body className={cousine.className}>
        <div className="dark:bg-gray-900 bg-gray-100  h-[100vh]">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
